// swift-tools-version: 5.9
import PackageDescription

// WalkMeEditor iOS SDK 1.1.0
// Generated by build_xcframeworks.sh — do not edit manually.
// Note: Lottie.framework must be linked manually by the host application.

let package = Package(
    name: "WalkMeEditor",
    products: [
        .library(name: "WalkMeEditor", targets: ["WalkMeEditor"])
    ],
    targets: [
        .binaryTarget(
            name: "WalkMeEditor",
            url: "https://github.com/abbiio/walkme-editor-native-ios/releases/download/1.0.17/WalkMeEditor.xcframework.zip",
            checksum: "e7f15ae647619fc62896bafcdf89b7f619a74055be1a63bb3c94d6c7e07c40b9"
        )
    ]
)
