// swift-tools-version: 5.9
import PackageDescription

// WalkMeEditor iOS SDK 1.1.0
// Generated by build_xcframeworks.sh — do not edit manually.
// Note: Lottie.framework must be linked manually by the host application.

let package = Package(
    name: "WalkMeEditor",
    products: [
        .library(name: "WalkMeEditor", targets: ["WalkMeEditor"])
    ],
    targets: [
        .binaryTarget(
            name: "WalkMeEditor",
            url: "https://github.com/WalkMe-int/walkme-ios-sdk-editor/releases/download/1.0.8/WalkMeEditor.xcframework.zip",
            checksum: "510cabc5ff9b55257dfcbe450d29583ca89d967a7ae3917cfc1bbf620fce4efb"
        )
    ]
)
