// swift-tools-version: 5.9
import PackageDescription

// WalkMeEditor iOS SDK 1.1.0
// Generated by build_xcframeworks.sh — do not edit manually.
// Note: Lottie.framework must be linked manually by the host application.

let package = Package(
    name: "WalkMeEditor",
    products: [
        .library(name: "WalkMeEditor", targets: ["WalkMeEditor"])
    ],
    targets: [
        .binaryTarget(
            name: "WalkMeEditor",
            url: "https://github.com/abbiio/walkme-editor-native-ios/releases/download/1.0.15/WalkMeEditor.xcframework.zip",
            checksum: "2fbf390ebb9ccbc6d1a4b9a27cdf365a09df2f80e657e4953b8d9b9cdcc7deb9"
        )
    ]
)
