//
//  WMView+WMUIGenerator.h
//  WalkMeSDK
//
//  Created by Haim Ben Chimol on 12/03/2019.
//  Copyright © 2019 WalkMe. All rights reserved.
//

#import <UIKit/UIKit.h>
#import "WMUIModelInterface.h"

NS_ASSUME_NONNULL_BEGIN

@class WMViewStyleObject;

@interface UIView (WMUIGenerator)

// Each view generated by WMUIGenerator will hold a reference to the model for easy access
@property (nonatomic,strong) id<WMUIModelInterface> __wm__UIModel;

// Activate / Deactivate layout constraints as described in the model's style
- (void)__wm__activateStyleConstraints;
- (void)__wm__deActivateStyleConstraints;

// TODO: refactoring: check if to remove from here, maybe category for NSLayoutConstraint
-(NSArray<NSLayoutConstraint*>*)__wm__positionConstraintsFrom:(WMViewStyleObject*)style superview:(UIView*)superview;

@end

NS_ASSUME_NONNULL_END
