#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.4 effective-5.10 (swiftlang-6.2.4.1.4 clang-1700.6.4.2)
#ifndef WALKMEEDITOR_SWIFT_H
#define WALKMEEDITOR_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#import <WalkMeEditor/WalkMeEditor.h>

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="WalkMeEditor",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

SWIFT_CLASS_NAMED("SwiftUIElementHandler")
@interface SwiftUIElementHandler : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class WMConditionNode;
SWIFT_CLASS("_TtC12WalkMeEditor29WMAppVerConditionNodeExecuter")
@interface WMAppVerConditionNodeExecuter : WMConditionNodeExecuter
- (BOOL)eval SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithConditionNode:(WMConditionNode * _Nonnull)conditionNode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSString;
@class NSCoder;
SWIFT_CLASS("_TtC12WalkMeEditor25WMAppVersionConditionNode")
@interface WMAppVersionConditionNode : WMConditionNode
@property (nonatomic, readonly, copy) NSString * _Nonnull funcName;
@property (nonatomic, readonly, copy) NSString * _Nonnull appVersion;
- (NSDictionary * _Nonnull)jsonMap SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithSerializableObject:(NSDictionary * _Nonnull)object version:(CGFloat)version OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)canSupportAction:(NSString * _Nonnull)actionName SWIFT_WARN_UNUSED_RESULT;
- (null_unspecified instancetype)initWithSerializableObject:(NSDictionary * _Null_unspecified)object SWIFT_UNAVAILABLE;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class WMStateMachineBase;
SWIFT_CLASS("_TtC12WalkMeEditor16WMBaseSDKManager")
@interface WMBaseSDKManager : NSObject
@property (nonatomic, strong) WMStateMachineBase * _Null_unspecified stateMachine;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class WalkMeStartOptions;
@class WMStateBase;
@interface WMBaseSDKManager (SWIFT_EXTENSION(WalkMeEditor))
- (void)startWithGUID:(NSString * _Nonnull)guid options:(WalkMeStartOptions * _Nullable)options;
/// Abstract — subclasses must override to return their target-specific active state.
- (WMStateBase * _Nonnull)makeActiveStateWithGuid:(NSString * _Nonnull)guid SWIFT_WARN_UNUSED_RESULT;
/// Optional hook for subclass-specific option application. Called during start(withGUID:options:).
- (void)applyStartOptions:(WalkMeStartOptions * _Nullable)options;
/// Optional hook for subclass-specific initialization options. Called during start(withGUID:options:).
- (void)applyAdditionalInitialization;
- (void)setUserAttributeWithKey:(NSString * _Nonnull)key andValue:(id _Nonnull)value;
- (void)setUserAttributes:(NSDictionary<NSString *, id> * _Nonnull)attributes;
- (void)setPrivateUserAttributeWithKey:(NSString * _Nonnull)key andValue:(id _Nonnull)value;
- (void)setPrivateUserAttributes:(NSDictionary<NSString *, id> * _Nonnull)attributes;
- (void)clearPrivateUserAttributes;
@end

@class NSNumber;
@class NSURLRequest;
@interface WMBaseSDKManager (SWIFT_EXTENSION(WalkMeEditor)) <WalkMeSDK>
- (void)start:(NSString * _Nonnull)settingsURL options:(WalkMeStartOptions * _Nullable)options;
- (void)restart:(WalkMeStartOptions * _Nullable)options;
- (BOOL)isRunning SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isActive:(NSError * _Nullable * _Nullable)error;
- (void)stop;
- (void)changeLanguage:(NSString * _Nonnull)language;
- (void)setWalkMeData:(NSString * _Nonnull)data forKey:(NSString * _Nonnull)key duration:(NSNumber * _Nonnull)duration;
- (void)setEndUserId:(NSString * _Nonnull)userId;
- (void)setAnalyticsMode:(WMAnalyticMode)mode;
- (void)setLoggingMode:(WMLoggingMode)mode;
- (void)setLoggingPath:(NSString * _Nonnull)path;
- (void)setStorageMode:(WMStorageMode)storageMode;
- (BOOL)isEditingState SWIFT_WARN_UNUSED_RESULT;
- (void)setProxy:(NSString * _Nonnull)url;
- (void)setHttpHeader:(NSString * _Nonnull)value forKey:(NSString * _Nonnull)key;
- (void)setRawHttpRequestCallback:(WMHTTPRequestCallback _Nonnull)requestCallback;
- (void)invokeRawHttpRequest:(NSURLRequest * _Nonnull)request;
@end

@class WMBasicPromotionObject;
@interface WMBusinessSolutionObject (SWIFT_EXTENSION(WalkMeEditor))
- (NSArray<NSString *> * _Nullable)swtConnectedPromotionIds SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, NSString *> * _Nonnull)swtConnectedPromoTypesFromPromos:(NSArray<WMBasicPromotionObject *> * _Nullable)promotions SWIFT_WARN_UNUSED_RESULT;
@end

@class UIColor;
@class UIEvent;
SWIFT_CLASS("_TtC12WalkMeEditor27WMCapturedElementBorderView")
@interface WMCapturedElementBorderView : UIView
@property (nonatomic) CGRect anchorFrame;
- (void)setStyleWithCornerRadius:(double)cornerRadius borderWidth:(double)borderWidth borderColor:(UIColor * _Nonnull)borderColor;
- (void)updateDrawing;
- (UIView * _Nullable)hitTest:(CGPoint)point withEvent:(UIEvent * _Nullable)event SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class WMWidgetObject;
SWIFT_CLASS("_TtC12WalkMeEditor20WMCarouselWidgetView")
@interface WMCarouselWidgetView : WMCanvasWidgetView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)layoutSubviews;
- (nonnull instancetype)initWithModel:(WMWidgetObject * _Nullable)model SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class UICollectionView;
@class UICollectionViewLayout;
@class NSIndexPath;
@interface WMCarouselWidgetView (SWIFT_EXTENSION(WalkMeEditor)) <UICollectionViewDelegateFlowLayout>
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end

@class UIScrollView;
@interface WMCarouselWidgetView (SWIFT_EXTENSION(WalkMeEditor)) <UICollectionViewDelegate>
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
@end

@class UICollectionViewCell;
@interface WMCarouselWidgetView (SWIFT_EXTENSION(WalkMeEditor)) <UICollectionViewDataSource>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end

enum WMDeployableType : NSInteger;
SWIFT_CLASS("_TtC12WalkMeEditor18WMDeployableHelper")
@interface WMDeployableHelper : NSObject
+ (NSString * _Nonnull)nameFor:(enum WMDeployableType)type SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)nameForRawValue:(NSInteger)rawValue SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, WMDeployableType, open) {
  WMDeployableTypeLauncher = 2,
  WMDeployableTypeShoutout = 14,
  WMDeployableTypeSwt = 19,
  WMDeployableTypeSurvey = 4,
};

SWIFT_CLASS("_TtC12WalkMeEditor25WMDeviceTypeConditionNode")
@interface WMDeviceTypeConditionNode : WMConditionNode
@property (nonatomic, readonly, copy) NSString * _Nonnull funcName;
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceType;
- (NSDictionary * _Nonnull)jsonMap SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithSerializableObject:(NSDictionary * _Nonnull)object version:(CGFloat)version OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)canSupportAction:(NSString * _Nonnull)actionName SWIFT_WARN_UNUSED_RESULT;
- (null_unspecified instancetype)initWithSerializableObject:(NSDictionary * _Null_unspecified)object SWIFT_UNAVAILABLE;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC12WalkMeEditor33WMDeviceTypeConditionNodeExecuter")
@interface WMDeviceTypeConditionNodeExecuter : WMConditionNodeExecuter
- (BOOL)eval SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithConditionNode:(WMConditionNode * _Nonnull)conditionNode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class WMEditorStateMachine;
SWIFT_CLASS("_TtC12WalkMeEditor15WMEditorManager")
@interface WMEditorManager : WMBaseSDKManager
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) WMEditorManager * _Nonnull shared;)
+ (WMEditorManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, strong) WMStateMachineBase * _Null_unspecified stateMachine;
@property (nonatomic, strong) WMEditorStateMachine * _Nonnull editorStateMachine;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface WMEditorManager (SWIFT_EXTENSION(WalkMeEditor)) <WalkMeiOSSDK>
- (WMStateBase * _Nonnull)makeActiveStateWithGuid:(NSString * _Nonnull)guid SWIFT_WARN_UNUSED_RESULT;
- (void)applyStartOptions:(WalkMeStartOptions * _Nullable)options;
- (void)stop;
- (void)applyAdditionalInitialization;
@end

@class WMElementDescription;
@class WMFEFlagsObject;
SWIFT_CLASS("_TtC12WalkMeEditor27WMElementClickConditionNode")
@interface WMElementClickConditionNode : WMConditionNode
@property (nonatomic, readonly, copy) NSString * _Nonnull funcName;
@property (nonatomic, readonly, strong) WMElementDescription * _Nullable data;
@property (nonatomic, readonly, strong) WMFEFlagsObject * _Nullable feFlags;
@property (nonatomic, readonly, copy) NSString * _Nonnull elementId;
- (NSDictionary * _Nonnull)jsonMap SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithSerializableObject:(NSDictionary * _Nonnull)object version:(CGFloat)version OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)canSupportAction:(NSString * _Nonnull)actionName SWIFT_WARN_UNUSED_RESULT;
- (null_unspecified instancetype)initWithSerializableObject:(NSDictionary * _Null_unspecified)object SWIFT_UNAVAILABLE;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class WMTouchEventsInspector;
SWIFT_CLASS("_TtC12WalkMeEditor35WMElementClickConditionNodeExecuter")
@interface WMElementClickConditionNodeExecuter : WMConditionNodeExecuter <WMTouchEventsInspectorDelegate>
- (nonnull instancetype)initWithConditionNode:(WMConditionNode * _Nonnull)conditionNode OBJC_DESIGNATED_INITIALIZER;
- (BOOL)eval SWIFT_WARN_UNUSED_RESULT;
- (void)asyncEval:(void (^ _Nonnull)(BOOL))completion;
- (void)touchInspector:(WMTouchEventsInspector * _Nonnull)touchInspector didTouchView:(UIView * _Nonnull)view pointInView:(CGPoint)pointInView pointInWindow:(CGPoint)pointInWindow touchType:(WMTouchEventTypeOption)touchType;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC12WalkMeEditor22WMElementConditionNode")
@interface WMElementConditionNode : WMConditionNode
@property (nonatomic, readonly, copy) NSString * _Nonnull funcName;
@property (nonatomic, readonly, strong) WMElementDescription * _Nullable data;
@property (nonatomic, readonly, strong) WMFEFlagsObject * _Nullable feFlags;
@property (nonatomic, readonly, copy) NSString * _Nonnull elementId;
@property (nonatomic, readonly, copy) NSString * _Nonnull elementText;
- (NSDictionary * _Nonnull)jsonMap SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithSerializableObject:(NSDictionary * _Nonnull)object version:(CGFloat)version OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)canSupportAction:(NSString * _Nonnull)actionName SWIFT_WARN_UNUSED_RESULT;
- (null_unspecified instancetype)initWithSerializableObject:(NSDictionary * _Null_unspecified)object SWIFT_UNAVAILABLE;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC12WalkMeEditor30WMElementConditionNodeExecuter")
@interface WMElementConditionNodeExecuter : WMConditionNodeExecuter
- (BOOL)eval SWIFT_WARN_UNUSED_RESULT;
- (void)asyncEval:(void (^ _Nonnull)(BOOL))completion;
- (nonnull instancetype)initWithConditionNode:(WMConditionNode * _Nonnull)conditionNode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("WMEventData")
@interface WMEventData : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum WMEventSendingMode : NSUInteger;
@class WMEventSession;
SWIFT_CLASS("_TtC12WalkMeEditor14WMEventManager")
@interface WMEventManager : NSObject
@property (nonatomic, readonly) enum WMEventSendingMode mode;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) WMEventManager * _Nonnull shared;)
+ (WMEventManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull sessionID;
@property (nonatomic, readonly, strong) WMEventSession * _Nullable currentSession;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (void)setEventManagerMode:(enum WMEventSendingMode)mode;
- (void)stop;
- (BOOL)shouldSendEvent SWIFT_WARN_UNUSED_RESULT;
@end

@class WMFlowNodeObject;
@class WMFlowObject;
@class WMEventPlayInitiatorData;
@class WMEventObject;
@class WMEventWalkmeData;
SWIFT_PROTOCOL("_TtP12WalkMeEditor22WMEventManagerProtocol_")
@protocol WMEventManagerProtocol
/// Set the events URL
- (void)setEventUrl:(NSString * _Nullable)url;
/// Nullify the current session
- (void)nullifySession;
/// Send a generic event with full parameters
- (void)sendEvent:(WMEventType)eventType forApp:(WMEventAppType)appType with:(WMBasicPromotionObject * _Nullable)promotionObj pinitType:(WMPlayInitiatorType)pinitType pinitAppType:(NSString * _Nullable)pinitAppType pinitID:(id _Nullable)pinitID triggeredApp:(WMEventAppType)triggeredApp triggeredObjID:(NSNumber * _Nullable)triggeredObjID reason:(WMEventCloseReason)reason;
/// Send a walkthrough event
- (void)sendWtEvent:(WMEventType)eventType with:(WMBasicPromotionObject * _Nullable)promotionObj firstNodeId:(NSNumber * _Nullable)firstNodeId pinitType:(WMPlayInitiatorType)pinitType pinitAppType:(NSString * _Nullable)pinitAppType pinitID:(id _Nullable)pinitID flowPlayID:(NSString * _Nullable)flowPlayID;
/// Send a walkthrough step event
- (void)sendEventForWtrStep:(WMFlowNodeObject * _Nullable)step flow:(WMFlowObject * _Nullable)flow status:(WMEventWtStepStatus)status value:(NSString * _Nullable)value flowPlayID:(NSString * _Nullable)flowPlayID;
/// Send a WalkMe-specific event
- (void)sendWalkmeEvent:(WMEventType)eventType value:(NSString * _Nullable)value;
/// Send an event with simplified parameters
- (void)sendEvent:(WMEventType)eventType forApp:(WMEventAppType)appType withName:(NSString * _Nullable)name objID:(NSNumber * _Nullable)objID value:(NSString * _Nullable)value initiatorData:(WMEventPlayInitiatorData * _Nullable)initiatorData;
/// Send a pre-constructed event object
- (void)sendEvent:(WMEventObject * _Nonnull)event;
/// Send event with custom data
- (void)sendEventWithData:(WMEventData * _Nonnull)eventData wmData:(WMEventWalkmeData * _Nullable)wmData type:(NSString * _Nullable)eventType;
/// Send event with session information
- (void)sendEvent:(WMEventType)eventType session:(WMEventSession * _Nonnull)session guid:(NSString * _Nonnull)guid;
/// The current event session object
@property (nonatomic, readonly, strong) WMEventSession * _Nullable currentSession;
/// Create a new event object
- (WMEventObject * _Nonnull)createEvent:(WMEventType)eventType forApp:(WMEventAppType)appType name:(NSString * _Nullable)name ID:(NSNumber * _Nullable)id SWIFT_WARN_UNUSED_RESULT;
/// Configure launcher-specific event details
- (void)setLauncherEvent:(WMEventObject * _Nonnull)event with:(WMBasicPromotionObject * _Nullable)promotionObj triggeredApp:(WMEventAppType)triggeredApp triggeredObjID:(NSNumber * _Nullable)triggeredObjID;
@end

@interface WMEventManager (SWIFT_EXTENSION(WalkMeEditor)) <WMEventManagerProtocol>
- (void)setEventUrl:(NSString * _Nullable)url;
- (void)nullifySession;
- (void)sendEvent:(WMEventType)eventType forApp:(WMEventAppType)appType with:(WMBasicPromotionObject * _Nullable)promotionObj pinitType:(WMPlayInitiatorType)pinitType pinitAppType:(NSString * _Nullable)pinitAppType pinitID:(id _Nullable)pinitID triggeredApp:(WMEventAppType)triggeredApp triggeredObjID:(NSNumber * _Nullable)triggeredObjID reason:(WMEventCloseReason)reason;
- (void)sendWtEvent:(WMEventType)eventType with:(WMBasicPromotionObject * _Nullable)promotionObj firstNodeId:(NSNumber * _Nullable)firstNodeId pinitType:(WMPlayInitiatorType)pinitType pinitAppType:(NSString * _Nullable)pinitAppType pinitID:(id _Nullable)pinitID flowPlayID:(NSString * _Nullable)flowPlayID;
- (void)sendEventForWtrStep:(WMFlowNodeObject * _Nullable)step flow:(WMFlowObject * _Nullable)flow status:(WMEventWtStepStatus)status value:(NSString * _Nullable)value flowPlayID:(NSString * _Nullable)flowPlayID;
- (void)sendWalkmeEvent:(WMEventType)eventType value:(NSString * _Nullable)value;
- (void)sendEvent:(WMEventType)eventType forApp:(WMEventAppType)appType withName:(NSString * _Nullable)name objID:(NSNumber * _Nullable)objID value:(NSString * _Nullable)value initiatorData:(WMEventPlayInitiatorData * _Nullable)initiatorData;
- (void)sendEvent:(WMEventObject * _Nonnull)event;
- (void)sendEventWithData:(WMEventData * _Nonnull)eventData wmData:(WMEventWalkmeData * _Nullable)wmData type:(NSString * _Nullable)eventType;
- (void)sendEvent:(WMEventType)eventType session:(WMEventSession * _Nonnull)session guid:(NSString * _Nonnull)guid;
- (WMEventObject * _Nonnull)createEvent:(WMEventType)eventType forApp:(WMEventAppType)appType name:(NSString * _Nullable)name ID:(NSNumber * _Nullable)id SWIFT_WARN_UNUSED_RESULT;
- (void)setLauncherEvent:(WMEventObject * _Nonnull)event with:(WMBasicPromotionObject * _Nullable)promotionObj triggeredApp:(WMEventAppType)triggeredApp triggeredObjID:(NSNumber * _Nullable)triggeredObjID;
@end

SWIFT_CLASS_NAMED("WMEventObject")
@interface WMEventObject : NSObject <NSCoding>
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
@end

SWIFT_CLASS_NAMED("WMEventPlayInitiatorData")
@interface WMEventPlayInitiatorData : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSUInteger, WMEventSendingMode, open) {
  WMEventSendingModeImmediately = 0,
  WMEventSendingModeAggregate = 1,
};

SWIFT_CLASS("_TtC12WalkMeEditor14WMEventSession")
@interface WMEventSession : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("WMEventWalkmeData")
@interface WMEventWalkmeData : NSObject
/// Set a new interaction GUID (e.g. when starting a new user interaction such as a promotion).
+ (void)setInteractionGuid;
/// Clear the current interaction GUID (e.g. when the interaction ends).
+ (void)resetInteractionGuid;
/// Current interaction GUID, or nil if reset. New instances use this value for interactionGuid.
+ (NSString * _Nullable)currentInteractionGuid SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSUInteger, WMEventWtStepType, open) {
  WMEventWtStepTypeNormal = 0,
  WMEventWtStepTypePopup = 1,
  WMEventWtStepTypeAction = 2,
};

@class WMVisualDesignObject;
@protocol WMUIActionHandlerInterface;
@class WMRootCanvasWidgetView;
SWIFT_CLASS("_TtC12WalkMeEditor17WMFlexUIGenerator")
@interface WMFlexUIGenerator : NSObject
+ (WMRootCanvasWidgetView * _Nonnull)generateFlexWithCanvas:(WMVisualDesignObject * _Nonnull)canvas handler:(id <WMUIActionHandlerInterface> _Nullable)handler SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol WMFlowPlayerDelgate;
@class WMNodeHandler;
@class WMNodeProgressData;
SWIFT_CLASS("_TtC12WalkMeEditor12WMFlowPlayer")
@interface WMFlowPlayer : WMPromotionPlayer <WMNodeHandlerDataSource>
@property (nonatomic, strong) id <WMFlowPlayerDelgate> _Nullable flowDelegate;
@property (nonatomic, strong) WMFlowObject * _Nonnull flow;
@property (nonatomic, strong) WMNodeHandler * _Nullable nodeHandler;
@property (nonatomic, strong) WMStack<WMNodeProgressData *> * _Nonnull flowStack;
@property (nonatomic, strong) WMStack<WMNodeProgressData *> * _Nonnull wtPathStack;
@property (nonatomic, strong) NSNumber * _Nonnull startingNodeId;
- (nonnull instancetype)initWithObject:(WMFlowObject * _Nonnull)flow startingNodeId:(NSNumber * _Nullable)startingNodeId OBJC_DESIGNATED_INITIALIZER;
- (void)onPlayerReady;
- (void)playPreviousStep;
- (void)playNextStep:(NSNumber * _Nullable)nodeId;
- (void)stop;
- (WMBasicPromotionObject * _Nonnull)promotion SWIFT_WARN_UNUSED_RESULT;
- (WMEventAppType)eventType SWIFT_WARN_UNUSED_RESULT;
- (WMFlowObject * _Nullable)flowInfo SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)flowPlayID SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isBackFromConnectedFlowStepItem:(WMNodeProgressData * _Nullable)currentStepItem toConnectedFlowStepItem:(WMNodeProgressData * _Nonnull)prevStepItem SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class WMFEResult;
@class WMViewActionObject;
@interface WMFlowPlayer (SWIFT_EXTENSION(WalkMeEditor)) <WMUIBasedNodeHandlerDelegate>
- (void)didDisplayNode:(WMFlowNodeObject * _Nonnull)node forElement:(WMFEResult * _Nullable)elementResult;
- (void)didFinishNode:(WMFlowNodeObject * _Nonnull)node withAction:(WMViewActionObject * _Nullable)action;
- (void)checkAndMarkAsDoneForNode:(WMFlowNodeObject * _Nonnull)node withAction:(WMViewActionObject * _Nullable)action;
@end

@interface WMFlowPlayer (SWIFT_EXTENSION(WalkMeEditor)) <WMConnectToFlowHandlerDelegate>
- (void)stepCancelled;
- (void)connectFlowId:(NSNumber * _Nonnull)flowId fromNode:(NSNumber * _Nonnull)nodeId nextNodeId:(NSNumber * _Nonnull)nextNodeId orgnNodeId:(NSNumber * _Nonnull)orgnNodeId;
- (void)connectShoutOutId:(NSNumber * _Nonnull)shoutOutId orgnNodeId:(NSNumber * _Nonnull)orgnNodeId;
@end

@class WMShoutOutObject;
SWIFT_PROTOCOL("_TtP12WalkMeEditor19WMFlowPlayerDelgate_")
@protocol WMFlowPlayerDelgate <WMPlayerDelegate>
@optional
- (void)flowPlayer:(WMFlowPlayer * _Nonnull)flowPlayer onWTDone:(WMFlowObject * _Nonnull)flow;
- (void)onMoveToStep:(NSDictionary * _Nonnull)stepData;
- (void)onStepDone:(NSDictionary * _Nonnull)stepData;
- (void)onStepShown:(NSDictionary * _Nonnull)stepData;
- (void)flowPlayerOnWTCancelled:(WMFlowPlayer * _Nonnull)flowPlayer;
- (WMFlowObject * _Nullable)onConnectToFlow:(NSNumber * _Nonnull)flowId SWIFT_WARN_UNUSED_RESULT;
- (WMShoutOutObject * _Nullable)onConnectToShoutOut:(NSNumber * _Nonnull)shoutOutId SWIFT_WARN_UNUSED_RESULT;
- (void)flowPlayer:(WMFlowPlayer * _Nonnull)flowPlayer willPlayConnectedDeployable:(WMBasicPromotionObject * _Nonnull)flow;
- (void)flowPlayer:(WMFlowPlayer * _Nonnull)flowPlayer didConnectToShoutOut:(WMShoutOutObject * _Nonnull)shoutOut;
@end

SWIFT_PROTOCOL("_TtP12WalkMeEditor32WMHybridAppScreenHandlerDelegate_")
@protocol WMHybridAppScreenHandlerDelegate <NSObject>
- (void)didChangeHybridAppScreen;
@end

SWIFT_CLASS("_TtC12WalkMeEditor16WMMethodSwizzler")
@interface WMMethodSwizzler : NSObject
+ (IMP _Nullable)replaceMethod:(SEL _Nonnull)aMethod inClass:(Class _Nonnull)origClass withMethod:(SEL _Nonnull)updatedMethod inClass:(Class _Nonnull)inspectorClass SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC12WalkMeEditor22WMNetworkConditionNode")
@interface WMNetworkConditionNode : WMConditionNode
@property (nonatomic, readonly, copy) NSString * _Nonnull funcName;
@property (nonatomic, readonly, copy) NSString * _Nonnull network;
- (NSDictionary * _Nonnull)jsonMap SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithSerializableObject:(NSDictionary * _Nonnull)object version:(CGFloat)version OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)canSupportAction:(NSString * _Nonnull)actionName SWIFT_WARN_UNUSED_RESULT;
- (null_unspecified instancetype)initWithSerializableObject:(NSDictionary * _Null_unspecified)object SWIFT_UNAVAILABLE;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC12WalkMeEditor30WMNetworkConditionNodeExecuter")
@interface WMNetworkConditionNodeExecuter : WMConditionNodeExecuter
- (BOOL)eval SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithConditionNode:(WMConditionNode * _Nonnull)conditionNode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC12WalkMeEditor31WMNumberOfSessionsConditionNode")
@interface WMNumberOfSessionsConditionNode : WMConditionNode
@property (nonatomic, readonly, copy) NSString * _Nonnull funcName;
@property (nonatomic, readonly, copy) NSString * _Nonnull numberOfSessions;
- (NSDictionary * _Nonnull)jsonMap SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithSerializableObject:(NSDictionary * _Nonnull)object version:(CGFloat)version OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)canSupportAction:(NSString * _Nonnull)actionName SWIFT_WARN_UNUSED_RESULT;
- (null_unspecified instancetype)initWithSerializableObject:(NSDictionary * _Null_unspecified)object SWIFT_UNAVAILABLE;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC12WalkMeEditor39WMNumberOfSessionsConditionNodeExecuter")
@interface WMNumberOfSessionsConditionNodeExecuter : WMConditionNodeExecuter
- (BOOL)eval SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithConditionNode:(WMConditionNode * _Nonnull)conditionNode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC12WalkMeEditor28WMOSVerConditionNodeExecuter")
@interface WMOSVerConditionNodeExecuter : WMConditionNodeExecuter
- (BOOL)eval SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithConditionNode:(WMConditionNode * _Nonnull)conditionNode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC12WalkMeEditor24WMOSVersionConditionNode")
@interface WMOSVersionConditionNode : WMConditionNode
@property (nonatomic, readonly, copy) NSString * _Nonnull funcName;
@property (nonatomic, readonly, copy) NSString * _Nonnull osVersion;
- (NSDictionary * _Nonnull)jsonMap SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithSerializableObject:(NSDictionary * _Nonnull)object version:(CGFloat)version OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)canSupportAction:(NSString * _Nonnull)actionName SWIFT_WARN_UNUSED_RESULT;
- (null_unspecified instancetype)initWithSerializableObject:(NSDictionary * _Null_unspecified)object SWIFT_UNAVAILABLE;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol WMPMDynamicAccessoryButtonViewDelegate;
enum WMPMCaptureMode : NSInteger;
SWIFT_CLASS("_TtC12WalkMeEditor28WMPMCaptureActionBarHostView")
@interface WMPMCaptureActionBarHostView : UIView
@property (nonatomic, weak) id <WMPMDynamicAccessoryButtonViewDelegate> _Nullable delegate;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER SWIFT_UNAVAILABLE;
- (void)configureWithCaptureMode:(enum WMPMCaptureMode)captureMode showCancel:(BOOL)showCancel showApprove:(BOOL)showApprove showRegionButtons:(BOOL)showRegionButtons canExpand:(BOOL)canExpand canNarrow:(BOOL)canNarrow isSWT:(BOOL)isSWT showDoneSWT:(BOOL)showDoneSWT;
- (void)updatePositionForMarkerFrame:(CGRect)markerFrame;
- (void)hideForMarkerDrag;
- (void)showAfterMarkerDrag;
@end

typedef SWIFT_ENUM(NSInteger, WMPMCaptureMode, open) {
  WMPMCaptureModeNavigate = 0,
  WMPMCaptureModePreciseCapture = 1,
};

SWIFT_CLASS("_TtC12WalkMeEditor28WMPMCaptureSWTWidgetHostView")
@interface WMPMCaptureSWTWidgetHostView : UIView
@property (nonatomic, copy) void (^ _Nullable onContinueOnCurrentScreen)(void);
@property (nonatomic, copy) void (^ _Nullable onDone)(void);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER SWIFT_UNAVAILABLE;
- (void)updatePositionRelativeTo:(CGRect)elementFrame;
@end

SWIFT_CLASS("_TtC12WalkMeEditor24WMPMDimmingHighlightView")
@interface WMPMDimmingHighlightView : UIView
@property (nonatomic) BOOL isDimmingVisible;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)updateWithElementFrame:(CGRect)elementFrame containerBounds:(CGRect)containerBounds;
- (void)setHighlightStyleWithCornerRadius:(double)cornerRadius borderWidth:(double)borderWidth borderColor:(UIColor * _Nonnull)borderColor;
- (void)remove;
- (UIView * _Nullable)hitTest:(CGPoint)point withEvent:(UIEvent * _Nullable)event SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(NSInteger, WMPMEditStepCaptureAction, open) {
  WMPMEditStepCaptureActionRecapture = 0,
  WMPMEditStepCaptureActionBefore = 1,
  WMPMEditStepCaptureActionAfter = 2,
};

SWIFT_CLASS("_TtC12WalkMeEditor14WMPMLoginState")
@interface WMPMLoginState : WMPMState
- (void)enter;
- (void)exit;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC12WalkMeEditor26WMPMMinimizedPanelHostView")
@interface WMPMMinimizedPanelHostView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end

@interface WMPMMinimizedPanelHostView (SWIFT_EXTENSION(WalkMeEditor))
- (void)configureMenuDisplayMode;
- (void)positionDockedTrailingIn:(UIView * _Nonnull)container topOffset:(CGFloat)topOffset;
- (void)redockIn:(UIView * _Nonnull)container;
- (void)setOnTap:(void (^ _Nonnull)(void))handler;
@end

@protocol WMPMPreciseCaptureViewDelegate;
@class UITouch;
SWIFT_CLASS("_TtC12WalkMeEditor22WMPMPreciseCaptureView")
@interface WMPMPreciseCaptureView : UIView
@property (nonatomic, weak) id <WMPMPreciseCaptureViewDelegate> _Nullable delegate;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)moveMarkerToPoint:(CGPoint)point;
- (void)touchesBegan:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)touchesMoved:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)touchesEnded:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)touchesCancelled:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
@end

SWIFT_PROTOCOL("_TtP12WalkMeEditor30WMPMPreciseCaptureViewDelegate_")
@protocol WMPMPreciseCaptureViewDelegate
@optional
- (void)preciseCaptureViewDidMove:(WMPMPreciseCaptureView * _Nonnull)preciseCaptureView;
- (void)preciseCaptureViewDidEndEditing:(WMPMPreciseCaptureView * _Nonnull)preciseCaptureView;
@end

@class UIAlertController;
SWIFT_CLASS("_TtC12WalkMeEditor9WMPMUtils")
@interface WMPMUtils : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull powerModeContextKey;)
+ (NSString * _Nonnull)powerModeContextKey SWIFT_WARN_UNUSED_RESULT;
+ (void)presentAlertController:(UIAlertController * _Nonnull)alertController withSourceView:(UIView * _Nullable)sourceView;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC12WalkMeEditor25WMPermissionConditionNode")
@interface WMPermissionConditionNode : WMConditionNode
@property (nonatomic, readonly, copy) NSString * _Nonnull funcName;
@property (nonatomic, readonly, copy) NSString * _Nonnull permissionStatus;
- (NSDictionary * _Nonnull)jsonMap SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithSerializableObject:(NSDictionary * _Nonnull)object version:(CGFloat)version OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)canSupportAction:(NSString * _Nonnull)actionName SWIFT_WARN_UNUSED_RESULT;
- (null_unspecified instancetype)initWithSerializableObject:(NSDictionary * _Null_unspecified)object SWIFT_UNAVAILABLE;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC12WalkMeEditor33WMPermissionConditionNodeExecuter")
@interface WMPermissionConditionNodeExecuter : WMConditionNodeExecuter
- (BOOL)eval SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithConditionNode:(WMConditionNode * _Nonnull)conditionNode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, WMPlayFrequency, open) {
  WMPlayFrequencyOncePerSession = 0,
  WMPlayFrequencyOnce = 1,
  WMPlayFrequencyAlways = 2,
};

typedef SWIFT_ENUM(NSInteger, WMPlayWaitInterval, open) {
  WMPlayWaitIntervalDays = 0,
  WMPlayWaitIntervalWeeks = 1,
  WMPlayWaitIntervalMonths = 2,
};

@class WMiOSPromotionsDataObject;
SWIFT_CLASS("_TtC12WalkMeEditor18WMPromotionManager")
@interface WMPromotionManager : NSObject
@property (nonatomic) BOOL isReady;
- (void)setupWithPromotions:(WMiOSPromotionsDataObject * _Nonnull)promotions;
- (void)clear;
@property (nonatomic, readonly) NSError * _Nullable isReadyError;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC12WalkMeEditor23WMPromotionRepeatObject")
@interface WMPromotionRepeatObject : NSObject
@property (nonatomic, readonly) enum WMPlayWaitInterval interval;
@property (nonatomic, readonly) NSInteger value;
- (nonnull instancetype)initWithDictionary:(NSDictionary * _Nonnull)dictionary OBJC_DESIGNATED_INITIALIZER;
- (BOOL)hasIntervalPassedSince:(NSTimeInterval)lastImpressionTime SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class WMConditionTree;
SWIFT_CLASS("_TtC12WalkMeEditor25WMPromotionSettingsObject")
@interface WMPromotionSettingsObject : NSObject
@property (nonatomic, readonly) BOOL isEnabled;
@property (nonatomic, readonly) BOOL isConditionTreeEnabled;
@property (nonatomic, readonly) enum WMPlayFrequency playFrequency;
@property (nonatomic, readonly) NSInteger totalPlaysLimit;
@property (nonatomic, readonly, strong) WMConditionTree * _Nullable conditionTree;
@property (nonatomic, readonly, strong) WMPromotionRepeatObject * _Nullable repeatConfig;
- (nonnull instancetype)initWithDictionary:(NSDictionary * _Nonnull)dictionary OBJC_DESIGNATED_INITIALIZER;
/// Init with separate settings dict and condition tree dict (for BusinessSolution where ASCT comes from a different path)
- (nonnull instancetype)initWithSettingsDictionary:(NSDictionary * _Nonnull)settingsDictionary conditionTreeDictionary:(NSDictionary * _Nullable)conditionTreeDictionary OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC12WalkMeEditor22WMRootCanvasWidgetView")
@interface WMRootCanvasWidgetView : WMCanvasWidgetView
- (void)layoutSubviews;
- (nonnull instancetype)initWithModel:(WMWidgetObject * _Nullable)model OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_PROTOCOL("_TtP12WalkMeEditor23WMScreenHandlerDelegate_")
@protocol WMScreenHandlerDelegate <NSObject>
@optional
@property (nonatomic, strong) id <WMHybridAppScreenHandlerDelegate> _Nullable hybridScreenHandlerDelegate;
@end

SWIFT_CLASS("_TtC12WalkMeEditor15WMScreenTracker")
@interface WMScreenTracker : NSObject
- (nonnull instancetype)initWithHybridScreenHandler:(id <WMScreenHandlerDelegate> _Nullable)hybridScreenHandler OBJC_DESIGNATED_INITIALIZER;
+ (NSString * _Nonnull)screenID SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nullable)availableScreenID SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)fromScreenID SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)screenFriendlyName SWIFT_WARN_UNUSED_RESULT;
+ (void)setUserScreenID:(NSString * _Nullable)screenID;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface WMScreenTracker (SWIFT_EXTENSION(WalkMeEditor)) <WMHybridAppScreenHandlerDelegate>
- (void)didChangeHybridAppScreen;
@end

@class UIViewController;
SWIFT_PROTOCOL("_TtP12WalkMeEditor35WMViewControllerInterceptorDelegate_")
@protocol WMViewControllerInterceptorDelegate <NSObject>
- (void)viewWillDisappearOn:(UIViewController * _Nonnull)vc animated:(BOOL)animated;
- (void)viewDidAppearOn:(UIViewController * _Nonnull)vc animated:(BOOL)animated;
- (void)viewDidDisappearOn:(UIViewController * _Nonnull)vc animated:(BOOL)animated;
@end

@interface WMScreenTracker (SWIFT_EXTENSION(WalkMeEditor)) <WMViewControllerInterceptorDelegate>
- (void)viewWillDisappearOn:(UIViewController * _Nonnull)vc animated:(BOOL)animated;
- (void)viewDidAppearOn:(UIViewController * _Nonnull)vc animated:(BOOL)animated;
- (void)viewDidDisappearOn:(UIViewController * _Nonnull)vc animated:(BOOL)animated;
@end

SWIFT_CLASS("_TtC12WalkMeEditor26WMSessionTimeConditionNode")
@interface WMSessionTimeConditionNode : WMConditionNode
@property (nonatomic, readonly, copy) NSString * _Nonnull funcName;
@property (nonatomic, readonly, copy) NSString * _Nonnull sessionTime;
- (NSDictionary * _Nonnull)jsonMap SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithSerializableObject:(NSDictionary * _Nonnull)object version:(CGFloat)version OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)canSupportAction:(NSString * _Nonnull)actionName SWIFT_WARN_UNUSED_RESULT;
- (null_unspecified instancetype)initWithSerializableObject:(NSDictionary * _Null_unspecified)object SWIFT_UNAVAILABLE;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC12WalkMeEditor34WMSessionTimeConditionNodeExecuter")
@interface WMSessionTimeConditionNodeExecuter : WMConditionNodeExecuter
- (BOOL)eval SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithConditionNode:(WMConditionNode * _Nonnull)conditionNode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class WMShoutOutPlayingItem;
@protocol WMShoutOutPlayerDelegate;
SWIFT_CLASS("_TtC12WalkMeEditor16WMShoutOutPlayer")
@interface WMShoutOutPlayer : WMPromotionPlayer
@property (nonatomic, readonly, strong) WMShoutOutObject * _Nonnull shoutOut;
@property (nonatomic, readonly, strong) WMShoutOutPlayingItem * _Nonnull so;
@property (nonatomic, weak) id <WMShoutOutPlayerDelegate> _Nullable shoutOutDelegate;
- (nonnull instancetype)initWithObject:(WMShoutOutPlayingItem * _Nonnull)so OBJC_DESIGNATED_INITIALIZER;
- (void)onPlayerReady;
- (void)stop;
- (WMBasicPromotionObject * _Nonnull)promotion SWIFT_WARN_UNUSED_RESULT;
- (WMEventAppType)eventType SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface WMShoutOutPlayer (SWIFT_EXTENSION(WalkMeEditor)) <WMUIActionHandlerInterface>
- (void)handle:(WMViewActionObject * _Nonnull)action onView:(UIView * _Nonnull)view;
@end

SWIFT_PROTOCOL("_TtP12WalkMeEditor24WMShoutOutPlayerDelegate_")
@protocol WMShoutOutPlayerDelegate <WMPlayerDelegate>
- (void)didFinishPlayingShoutOut:(WMShoutOutPlayer * _Nonnull)player dismissType:(WMSODismissType)dismissType;
@end

@protocol WMFEResultInterface;
@protocol WMStepTriggerHandlerInterface;
SWIFT_CLASS("_TtC12WalkMeEditor27WMStepTriggerHandlerFactory")
@interface WMStepTriggerHandlerFactory : NSObject
+ (NSArray<id <WMStepTriggerHandlerInterface>> * _Nullable)handlersForElement:(id <WMFEResultInterface> _Nonnull)element delegate:(id _Nonnull)delegate SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol WMUIVisualDesignInterface;
@class WMTooltipObject;
@class WMBalloonAnchorView;
SWIFT_CLASS("_TtC12WalkMeEditor13WMUIGenerator")
@interface WMUIGenerator : NSObject
+ (WMCanvasWidgetView * _Nullable)generateCanvas:(id <WMUIVisualDesignInterface> _Nonnull)canvas parentBounds:(CGRect)parentBounds uiActionHandler:(id <WMUIActionHandlerInterface> _Nullable)uiActionHandler SWIFT_WARN_UNUSED_RESULT;
+ (WMCanvasWidgetView * _Nullable)generateCanvas:(id <WMUIVisualDesignInterface> _Nonnull)canvas parentBounds:(CGRect)parentBounds uiActionHandler:(id <WMUIActionHandlerInterface> _Nullable)uiActionHandler into:(UIView * _Nonnull)parentView SWIFT_WARN_UNUSED_RESULT;
+ (WMBalloonAnchorView * _Nullable)generateBalloonFor:(WMWidgetObjectType)type canvasView:(WMCanvasWidgetView * _Nonnull)canvasView anchorView:(UIView * _Nonnull)anchorView model:(WMTooltipObject * _Nonnull)model SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol WMStorageManagerProtocol;
SWIFT_CLASS("_TtC12WalkMeEditor24WMUnifiedPromotionPlayer")
@interface WMUnifiedPromotionPlayer : NSObject
/// Forwarding delegate for action-triggered playback (shouldPlayFlow, shouldPlayShoutout, etc.)
@property (nonatomic, weak) id <WMPlayerDelegate> _Nullable actionDelegate;
/// Called when the player finishes for any reason
@property (nonatomic, copy) void (^ _Nullable onStop)(void);
/// After stop — the shoutout dismiss type (only meaningful for shoutOut kind)
@property (nonatomic, readonly) WMSODismissType lastDismissType;
/// The playing item (only for shoutOut kind, used by manager for queue advancement)
@property (nonatomic, readonly, strong) WMShoutOutPlayingItem * _Nullable shoutOutPlayingItem;
/// The promotion object being played
@property (nonatomic, readonly, strong) WMBasicPromotionObject * _Nullable promotion;
+ (WMUnifiedPromotionPlayer * _Nonnull)forFlow:(WMBusinessSolutionObject * _Nonnull)bs startingNodeId:(NSNumber * _Nullable)startingNodeId storageManager:(id <WMStorageManagerProtocol> _Nonnull)storageManager dataSource:(WMBasicPromotionObject * _Nullable (^ _Nonnull)(NSInteger))dataSource SWIFT_WARN_UNUSED_RESULT;
+ (WMUnifiedPromotionPlayer * _Nonnull)forShoutOut:(WMShoutOutPlayingItem * _Nonnull)soPlayingItem storageManager:(id <WMStorageManagerProtocol> _Nonnull)storageManager dataSource:(WMBasicPromotionObject * _Nullable (^ _Nonnull)(NSInteger))dataSource SWIFT_WARN_UNUSED_RESULT;
- (void)play;
- (void)stop;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface WMUnifiedPromotionPlayer (SWIFT_EXTENSION(WalkMeEditor)) <WMShoutOutPlayerDelegate>
- (void)didFinishPlayingShoutOut:(WMShoutOutPlayer * _Nonnull)player dismissType:(WMSODismissType)dismissType;
- (void)shouldDismissWithShoutOut:(WMShoutOutPlayer * _Nonnull)player;
@end

@interface WMUnifiedPromotionPlayer (SWIFT_EXTENSION(WalkMeEditor)) <WMFlowPlayerDelgate>
- (WMFlowObject * _Nullable)onConnectToFlow:(NSNumber * _Nonnull)flowId SWIFT_WARN_UNUSED_RESULT;
- (WMShoutOutObject * _Nullable)onConnectToShoutOut:(NSNumber * _Nonnull)shoutOutId SWIFT_WARN_UNUSED_RESULT;
- (void)flowPlayerOnWTCancelled:(WMFlowPlayer * _Nonnull)flowPlayer;
- (void)flowPlayer:(WMFlowPlayer * _Nonnull)flowPlayer onWTDone:(WMFlowObject * _Nonnull)flow;
- (void)flowPlayer:(WMFlowPlayer * _Nonnull)flowPlayer willPlayConnectedDeployable:(WMBasicPromotionObject * _Nonnull)flow;
- (void)flowPlayer:(WMFlowPlayer * _Nonnull)flowPlayer didConnectToShoutOut:(WMShoutOutObject * _Nonnull)shoutOut;
- (void)onMoveToStep:(NSDictionary * _Nonnull)stepData;
- (void)onStepDone:(NSDictionary * _Nonnull)stepData;
@end

SWIFT_CLASS("_TtC12WalkMeEditor21WMUserIdConditionNode")
@interface WMUserIdConditionNode : WMConditionNode
@property (nonatomic, readonly, copy) NSString * _Nonnull funcName;
@property (nonatomic, readonly, copy) NSString * _Nonnull userId;
- (NSDictionary * _Nonnull)jsonMap SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithSerializableObject:(NSDictionary * _Nonnull)object version:(CGFloat)version OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)canSupportAction:(NSString * _Nonnull)actionName SWIFT_WARN_UNUSED_RESULT;
- (null_unspecified instancetype)initWithSerializableObject:(NSDictionary * _Null_unspecified)object SWIFT_UNAVAILABLE;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC12WalkMeEditor29WMUserIdConditionNodeExecuter")
@interface WMUserIdConditionNodeExecuter : WMConditionNodeExecuter
- (BOOL)eval SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithConditionNode:(WMConditionNode * _Nonnull)conditionNode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC12WalkMeEditor27WMViewControllerInterceptor")
@interface WMViewControllerInterceptor : NSObject
@property (nonatomic, weak) id <WMViewControllerInterceptorDelegate> _Nullable delegate;
- (nonnull instancetype)initWithDelegate:(id <WMViewControllerInterceptorDelegate> _Nonnull)delegate OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class WMViewAnimationObject;
SWIFT_CLASS("_TtC12WalkMeEditor18WMVisualDesignView")
@interface WMVisualDesignView : WMAnimatableView
@property (nonatomic, readonly, strong) WMViewAnimationObject * _Nullable animation;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS("_TtC12WalkMeEditor15WalkMePowerMode")
@interface WalkMePowerMode : NSObject
+ (void)startWithGUID:(NSString * _Nonnull)guid options:(WalkMeStartOptions * _Nullable)options;
+ (void)stop;
+ (void)setUserAttributeWithKey:(NSString * _Nonnull)key value:(id _Nonnull)value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
